irregular_verbs = {
"andar": [{'pattern': 'andar', 'stems': ['and']}],
"desandar": [{'pattern': 'andar', 'stems': ['desand']}],
"dar": [{'pattern': 'dar', 'stems': ['d']}],
"errar": [{'pattern': 'errar', 'stems': ['']}],
"estar": [{'pattern': 'estar', 'stems': ['est']}],
"jugar": [{'pattern': 'jugar', 'stems': ['j', 'g']}],
"adaguar": [{'pattern': '-guar', 'stems': ['ada']}],
"aguar": [{'pattern': '-guar', 'stems': ['a']}],
"amenguar": [{'pattern': '-guar', 'stems': ['amen']}],
"amortiguar": [{'pattern': '-guar', 'stems': ['amorti']}],
"antiguar": [{'pattern': '-guar', 'stems': ['anti']}],
"apaciguar": [{'pattern': '-guar', 'stems': ['apaci']}],
"apaniguar": [{'pattern': '-guar', 'stems': ['apani']}],
"atestiguar": [{'pattern': '-guar', 'stems': ['atesti']}],
"atreguar": [{'pattern': '-guar', 'stems': ['atre']}],
"averiguar": [{'pattern': '-guar', 'stems': ['averi']}],
"desaguar": [{'pattern': '-guar', 'stems': ['desa']}],
"desambiguar": [{'pattern': '-guar', 'stems': ['desambi']}],
"deslenguar": [{'pattern': '-guar', 'stems': ['deslen']}],
"enjaguar": [{'pattern': '-guar', 'stems': ['enja']}],
"fraguar": [{'pattern': '-guar', 'stems': ['fra']}],
"menguar": [{'pattern': '-guar', 'stems': ['men']}],
"santiguar": [{'pattern': '-guar', 'stems': ['santi']}],
"testiguar": [{'pattern': '-guar', 'stems': ['testi']}],
"academizar": [{'pattern': '-izar', 'stems': ['academ']}],
"enraizar": [{'pattern': '-izar', 'stems': ['enra']}],
"europeizar": [{'pattern': '-izar', 'stems': ['europe']}],
"plurinacionalizar": [{'pattern': '-izar', 'stems': ['plurinacional']}],
"tematizar": [{'pattern': '-izar', 'stems': ['temat']}],
"acertar": [{'pattern': 'e-ie', 'stems': ['ac', 'rt']}],
"acrecentar": [{'pattern': 'e-ie', 'stems': ['acrec', 'nt']}],
"adestrar": [{'pattern': 'e-ie', 'stems': ['ad', 'str']}],
"aferrar": [{'pattern': '', 'stems': ['aferr']}, {'pattern': 'e-ie', 'stems': ['af', 'rr']}],
"alentar": [{'pattern': 'e-ie', 'stems': ['al', 'nt']}],
"aneblar": [{'pattern': 'e-ie', 'stems': ['an', 'bl']}],
"apacentar": [{'pattern': 'e-ie', 'stems': ['apac', 'nt']}],
"apretar": [{'pattern': 'e-ie', 'stems': ['apr', 't']}],
"arrendar": [{'pattern': 'e-ie', 'stems': ['arr', 'nd']}, {'pattern': '', 'stems': ['arrend']}],
"asentar": [{'pattern': 'e-ie', 'stems': ['as', 'nt']}],
"atentar": [{'pattern': '', 'stems': ['atent']}, {'pattern': 'e-ie', 'stems': ['at', 'nt']}],
"aterrar": [{'pattern': 'e-ie', 'stems': ['at', 'rr']}, {'pattern': '', 'stems': ['aterr']}],
"atesar": [{'pattern': 'e-ie', 'stems': ['at', 's']}],
"atestar": [{'pattern': 'e-ie', 'stems': ['at', 'st']}],
"atravesar": [{'pattern': 'e-ie', 'stems': ['atrav', 's']}],
"autogobernar": [{'pattern': 'e-ie', 'stems': ['autogob', 'rn']}],
"avalentar": [{'pattern': 'e-ie', 'stems': ['aval', 'nt']}],
"aventar": [{'pattern': 'e-ie', 'stems': ['av', 'nt']}],
"calentar": [{'pattern': 'e-ie', 'stems': ['cal', 'nt']}],
"cerrar": [{'pattern': 'e-ie', 'stems': ['c', 'rr']}],
"cimentar": [{'pattern': 'e-ie', 'stems': ['cim', 'nt']}],
"cogobernar": [{'pattern': 'e-ie', 'stems': ['cogob', 'rn']}],
"concertar": [{'pattern': 'e-ie', 'stems': ['conc', 'rt']}],
"confesar": [{'pattern': 'e-ie', 'stems': ['conf', 's']}],
"dentar": [{'pattern': 'e-ie', 'stems': ['d', 'nt']}],
"desacertar": [{'pattern': 'e-ie', 'stems': ['desac', 'rt']}],
"desalentar": [{'pattern': 'e-ie', 'stems': ['desal', 'nt']}],
"desatentar": [{'pattern': 'e-ie', 'stems': ['desat', 'nt']}],
"desconcertar": [{'pattern': 'e-ie', 'stems': ['desconc', 'rt']}],
"desencerrar": [{'pattern': 'e-ie', 'stems': ['desenc', 'rr']}],
"desenterrar": [{'pattern': 'e-ie', 'stems': ['desent', 'rr']}],
"desgobernar": [{'pattern': 'e-ie', 'stems': ['desgob', 'rn']}],
"deshelar": [{'pattern': 'e-ie', 'stems': ['desh', 'l']}],
"desmembrar": [{'pattern': 'e-ie', 'stems': ['desm', 'mbr']}],
"despertar": [{'pattern': 'e-ie', 'stems': ['desp', 'rt']}],
"desterrar": [{'pattern': 'e-ie', 'stems': ['dest', 'rr']}],
"desventar": [{'pattern': 'e-ie', 'stems': ['desv', 'nt']}],
"dezmar": [{'pattern': 'e-ie', 'stems': ['d', 'zm']}],
"emparentar": [{'pattern': 'e-ie', 'stems': ['empar', 'nt']}, {'pattern': '', 'stems': ['emparent']}],
"empedrar": [{'pattern': 'e-ie', 'stems': ['emp', 'dr']}],
"encerrar": [{'pattern': 'e-ie', 'stems': ['enc', 'rr']}],
"encomendar": [{'pattern': 'e-ie', 'stems': ['encom', 'nd']}],
"encubertar": [{'pattern': 'e-ie', 'stems': ['encub', 'rt']}],
"enmendar": [{'pattern': 'e-ie', 'stems': ['enm', 'nd']}],
"ensangrentar": [{'pattern': 'e-ie', 'stems': ['ensangr', 'nt']}],
"enterrar": [{'pattern': 'e-ie', 'stems': ['ent', 'rr']}],
"entrecerrar": [{'pattern': 'e-ie', 'stems': ['entrec', 'rr']}],
"escalentar": [{'pattern': 'e-ie', 'stems': ['escal', 'nt']}],
"escarmentar": [{'pattern': 'e-ie', 'stems': ['escarm', 'nt']}],
"gobernar": [{'pattern': 'e-ie', 'stems': ['gob', 'rn']}],
"hacendar": [{'pattern': 'e-ie', 'stems': ['hac', 'nd']}],
"helar": [{'pattern': 'e-ie', 'stems': ['h', 'l']}],
"herbar": [{'pattern': 'e-ie', 'stems': ['h', 'rb']}],
"herrar": [{'pattern': 'e-ie', 'stems': ['h', 'rr']}],
"hibernar": [{'pattern': '', 'stems': ['hibern']}, {'pattern': 'e-ie', 'stems': ['hib', 'rn']}],
"invernar": [{'pattern': 'e-ie', 'stems': ['inv', 'rn']}, {'pattern': '', 'stems': ['invern']}],
"manifestar": [{'pattern': 'e-ie', 'stems': ['manif', 'st']}],
"melar": [{'pattern': 'e-ie', 'stems': ['m', 'l']}],
"mentar": [{'pattern': 'e-ie', 'stems': ['m', 'nt']}],
"merendar": [{'pattern': 'e-ie', 'stems': ['mer', 'nd']}],
"nevar": [{'pattern': 'e-ie', 'stems': ['n', 'v']}],
"pensar": [{'pattern': 'e-ie', 'stems': ['p', 'ns']}],
"precalentar": [{'pattern': 'e-ie', 'stems': ['precal', 'nt']}],
"quebrar": [{'pattern': 'e-ie', 'stems': ['qu', 'br']}],
"recalentar": [{'pattern': 'e-ie', 'stems': ['recal', 'nt']}],
"recentar": [{'pattern': 'e-ie', 'stems': ['rec', 'nt']}],
"recomendar": [{'pattern': 'e-ie', 'stems': ['recom', 'nd']}],
"reenterrar": [{'pattern': 'e-ie', 'stems': ['reent', 'rr']}],
"remendar": [{'pattern': 'e-ie', 'stems': ['rem', 'nd']}],
"repensar": [{'pattern': 'e-ie', 'stems': ['rep', 'ns']}],
"requebrar": [{'pattern': 'e-ie', 'stems': ['requ', 'br']}],
"resembrar": [{'pattern': 'e-ie', 'stems': ['res', 'mbr']}],
"retemblar": [{'pattern': 'e-ie', 'stems': ['ret', 'mbl']}],
"reventar": [{'pattern': 'e-ie', 'stems': ['rev', 'nt']}],
"salpimentar": [{'pattern': 'e-ie', 'stems': ['salpim', 'nt']}],
"sarmentar": [{'pattern': 'e-ie', 'stems': ['sarm', 'nt']}],
"sembrar": [{'pattern': 'e-ie', 'stems': ['s', 'mbr']}],
"sementar": [{'pattern': 'e-ie', 'stems': ['sem', 'nt']}],
"sentar": [{'pattern': 'e-ie', 'stems': ['s', 'nt']}],
"serrar": [{'pattern': 'e-ie', 'stems': ['s', 'rr']}],
"sobrecalentar": [{'pattern': 'e-ie', 'stems': ['sobrecal', 'nt']}],
"soterrar": [{'pattern': 'e-ie', 'stems': ['sot', 'rr']}],
"subarrendar": [{'pattern': 'e-ie', 'stems': ['subarr', 'nd']}],
"temblar": [{'pattern': 'e-ie', 'stems': ['t', 'mbl']}],
"tentar": [{'pattern': 'e-ie', 'stems': ['t', 'nt']}],
"ventar": [{'pattern': 'e-ie', 'stems': ['v', 'nt']}],
"agorar": [{'pattern': 'go-güe', 'stems': ['ag', 'r']}],
"degollar": [{'pattern': 'go-güe', 'stems': ['deg', 'll']}],
"regoldar": [{'pattern': 'go-güe', 'stems': ['reg', 'ld']}],
"adiar": [{'pattern': 'i-í', 'stems': ['ad', '']}],
"agraviar": [{'pattern': 'i-í', 'stems': ['agrav', '']}],
"agriar": [{'pattern': 'i-í', 'stems': ['agr', '']}],
"ahijar": [{'pattern': 'i-í', 'stems': ['ah', 'j']}],
"ahilar": [{'pattern': 'i-í', 'stems': ['ah', 'l']}],
"ahitar": [{'pattern': 'i-í', 'stems': ['ah', 't']}],
"airar": [{'pattern': 'i-í', 'stems': ['a', 'r']}],
"aislar": [{'pattern': 'i-í', 'stems': ['a', 'sl']}],
"aliar": [{'pattern': 'i-í', 'stems': ['al', '']}],
"amnistiar": [{'pattern': 'i-í', 'stems': ['amnist', '']}],
"amohinar": [{'pattern': 'i-í', 'stems': ['amoh', 'n']}],
"ampliar": [{'pattern': 'i-í', 'stems': ['ampl', '']}],
"ansiar": [{'pattern': 'i-í', 'stems': ['ans', '']}],
"arriar": [{'pattern': 'i-í', 'stems': ['arr', '']}],
"ataviar": [{'pattern': 'i-í', 'stems': ['atav', '']}],
"atraillar": [{'pattern': 'i-í', 'stems': ['atra', 'll']}],
"autoaislarse": [{'pattern': 'i-í', 'stems': ['autoa', 'sl']}],
"autografiar": [{'pattern': 'i-í', 'stems': ['autograf', '']}],
"averiar": [{'pattern': 'i-í', 'stems': ['aver', '']}],
"aviar": [{'pattern': 'i-í', 'stems': ['av', '']}],
"baquiar": [{'pattern': 'i-í', 'stems': ['baqu', '']}],
"biografiar": [{'pattern': 'i-í', 'stems': ['biograf', '']}],
"cablegrafiar": [{'pattern': 'i-í', 'stems': ['cablegraf', '']}],
"caligrafiar": [{'pattern': 'i-í', 'stems': ['caligraf', '']}],
"cariar": [{'pattern': 'i-í', 'stems': ['car', '']}],
"cartografiar": [{'pattern': 'i-í', 'stems': ['cartograf', '']}],
"chirriar": [{'pattern': 'i-í', 'stems': ['chirr', '']}],
"ciar": [{'pattern': 'i-í unstressed', 'stems': ['c', '']}],
"cinematografiar": [{'pattern': 'i-í', 'stems': ['cinematograf', '']}],
"confiar": [{'pattern': 'i-í', 'stems': ['conf', '']}],
"contrariar": [{'pattern': 'i-í', 'stems': ['contrar', '']}],
"coreografiar": [{'pattern': 'i-í', 'stems': ['coreograf', '']}],
"criar": [{'pattern': 'i-í unstressed', 'stems': ['cr', '']}],
"culiar": [{'pattern': 'i-í', 'stems': ['cul', '']}],
"dactilografiar": [{'pattern': 'i-í', 'stems': ['dactilograf']}],
"desafiar": [{'pattern': 'i-í', 'stems': ['desaf', '']}],
"desahijar": [{'pattern': 'i-í', 'stems': ['desah', 'j']}],
"desainar": [{'pattern': 'i-í', 'stems': ['desa', 'n']}],
"desairar": [{'pattern': 'i-í', 'stems': ['desa', 'r']}],
"desatraillar": [{'pattern': 'i-í', 'stems': ['desatra', 'll']}],
"descafeinar": [{'pattern': 'i-í', 'stems': ['descafe', 'n']}],
"descarriar": [{'pattern': 'i-í', 'stems': ['descarr', '']}],
"desconfiar": [{'pattern': 'i-í', 'stems': ['desconf', '']}],
"desliar": [{'pattern': 'i-í', 'stems': ['desl']}],
"desvariar": [{'pattern': 'i-í', 'stems': ['desvar']}],
"desviar": [{'pattern': 'i-í', 'stems': ['desv', '']}],
"ejecutoriar": [{'pattern': 'i-í', 'stems': ['ejecutor']}, {'pattern': '', 'stems': ['ejecutori']}],
"enbiar": [{'pattern': 'i-í', 'stems': ['enb', '']}],
"enfriar": [{'pattern': 'i-í', 'stems': ['enfr', '']}],
"enviar": [{'pattern': 'i-í', 'stems': ['env', '']}],
"escalofriar": [{'pattern': 'i-í', 'stems': ['escalofr']}],
"esgrafiar": [{'pattern': 'i-í', 'stems': ['esgraf']}],
"espiar": [{'pattern': 'i-í', 'stems': ['esp', '']}],
"esquiar": [{'pattern': 'i-í', 'stems': ['esqu', '']}],
"estriar": [{'pattern': 'i-í', 'stems': ['estr', '']}],
"expatriar": [{'pattern': 'i-í', 'stems': ['expatr', '']}],
"expiar": [{'pattern': 'i-í', 'stems': ['exp', '']}],
"extraviar": [{'pattern': 'i-í', 'stems': ['extrav', '']}],
"fiar": [{'pattern': 'i-í unstressed', 'stems': ['f', '']}],
"fotografiar": [{'pattern': 'i-í', 'stems': ['fotograf', '']}],
"guiar": [{'pattern': 'i-í unstressed', 'stems': ['gu', '']}],
"hastiar": [{'pattern': 'i-í', 'stems': ['hast', '']}],
"historiar": [{'pattern': 'i-í', 'stems': ['histor', '']}],
"inventariar": [{'pattern': 'i-í', 'stems': ['inventar', '']}],
"liar": [{'pattern': 'i-í unstressed', 'stems': ['l', '']}],
"malcriar": [{'pattern': 'i-í', 'stems': ['malcr']}],
"mimeografiar": [{'pattern': 'i-í', 'stems': ['mimeograf', '']}],
"paliar": [{'pattern': 'i-í', 'stems': ['pal', '']}],
"piar": [{'pattern': 'i-í unstressed', 'stems': ['p', '']}],
"pipiar": [{'pattern': 'i-í', 'stems': ['pip', '']}],
"porfiar": [{'pattern': 'i-í', 'stems': ['porf', '']}],
"prohijar": [{'pattern': 'i-í', 'stems': ['proh', 'j']}],
"radiografiar": [{'pattern': 'i-í', 'stems': ['radiograf', '']}],
"recriar": [{'pattern': 'i-í', 'stems': ['recr', '']}],
"reenviar": [{'pattern': 'i-í', 'stems': ['reenv', '']}],
"refotografiar": [{'pattern': 'i-í', 'stems': ['refotograf', '']}],
"rehilar": [{'pattern': 'i-í', 'stems': ['reh', 'l']}],
"repatriar": [{'pattern': 'i-í', 'stems': ['repatr', '']}, {'pattern': '', 'stems': ['repatri']}],
"resfriar": [{'pattern': 'i-í', 'stems': ['resfr', '']}],
"rociar": [{'pattern': 'i-í', 'stems': ['roc', '']}],
"telegrafiar": [{'pattern': 'i-í', 'stems': ['telegraf', '']}],
"vaciar": [{'pattern': 'i-í', 'stems': ['vac', '']}],
"variar": [{'pattern': 'i-í', 'stems': ['var', '']}],
"xerografiar": [{'pattern': 'i-í', 'stems': ['xerograf', '']}],
"zurriar": [{'pattern': 'i-í', 'stems': ['zurr', '']}],
"desosar": [{'pattern': 'o-hue', 'stems': ['des', 's']}],
"abuñolar": [{'pattern': 'o-ue', 'stems': ['abuñ', 'l']}],
"acordar": [{'pattern': 'o-ue', 'stems': ['ac', 'rd']}],
"acostar": [{'pattern': 'o-ue', 'stems': ['ac', 'st']}],
"aforar": [{'pattern': '', 'stems': ['afor']}, {'pattern': 'o-ue', 'stems': ['af', 'r']}],
"amoblar": [{'pattern': 'o-ue', 'stems': ['am', 'bl']}],
"amolar": [{'pattern': 'o-ue', 'stems': ['am', 'l']}],
"apostar": [{'pattern': 'o-ue', 'stems': ['ap', 'st']}, {'pattern': '', 'stems': ['apost']}],
"aprobar": [{'pattern': 'o-ue', 'stems': ['apr', 'b']}],
"asolar": [{'pattern': 'o-ue', 'stems': ['as', 'l']}, {'pattern': '', 'stems': ['asol']}],
"atronar": [{'pattern': 'o-ue', 'stems': ['atr', 'n']}],
"circunvolar": [{'pattern': 'o-ue', 'stems': ['circunv', 'l']}],
"colar": [{'pattern': 'o-ue', 'stems': ['c', 'l']}],
"comprobar": [{'pattern': 'o-ue', 'stems': ['compr', 'b']}],
"concordar": [{'pattern': 'o-ue', 'stems': ['conc', 'rd']}],
"consolar": [{'pattern': 'o-ue', 'stems': ['cons', 'l']}],
"consonar": [{'pattern': 'o-ue', 'stems': ['cons', 'n']}],
"contar": [{'pattern': 'o-ue', 'stems': ['c', 'nt']}],
"costar": [{'pattern': 'o-ue', 'stems': ['c', 'st']}],
"demostrar": [{'pattern': 'o-ue', 'stems': ['dem', 'str']}],
"denostar": [{'pattern': 'o-ue', 'stems': ['den', 'st']}],
"desacordar": [{'pattern': 'o-ue', 'stems': ['desac', 'rd']}],
"desaforar": [{'pattern': 'o-ue', 'stems': ['desaf', 'r']}, {'pattern': '', 'stems': ['desafor']}],
"desaprobar": [{'pattern': 'o-ue', 'stems': ['desapr', 'b']}],
"descollar": [{'pattern': 'o-ue', 'stems': ['desc', 'll']}],
"desconsolar": [{'pattern': 'o-ue', 'stems': ['descons', 'l']}],
"descontar": [{'pattern': 'o-ue', 'stems': ['desc', 'nt']}],
"descornar": [{'pattern': 'o-ue', 'stems': ['desc', 'rn']}],
"desencontrarse": [{'pattern': 'o-ue', 'stems': ['desenc', 'ntr']}],
"desolar": [{'pattern': 'o-ue', 'stems': ['des', 'l']}],
"desoldar": [{'pattern': 'o-ue', 'stems': ['des', 'ld']}],
"desollar": [{'pattern': 'o-ue', 'stems': ['des', 'll']}],
"despoblar": [{'pattern': 'o-ue', 'stems': ['desp', 'bl']}],
"discordar": [{'pattern': 'o-ue', 'stems': ['disc', 'rd']}],
"disonar": [{'pattern': 'o-ue', 'stems': ['dis', 'n']}],
"dolar": [{'pattern': 'o-ue', 'stems': ['d', 'l']}],
"encontrar": [{'pattern': 'o-ue', 'stems': ['enc', 'ntr']}],
"encordar": [{'pattern': 'o-ue', 'stems': ['enc', 'rd']}],
"engrosar": [{'pattern': 'o-ue', 'stems': ['engr', 's']}, {'pattern': '', 'stems': ['engros']}],
"ensoñar": [{'pattern': 'o-ue', 'stems': ['ens', 'ñ']}],
"hollar": [{'pattern': 'o-ue', 'stems': ['h', 'll']}],
"improbar": [{'pattern': 'o-ue', 'stems': ['impr', 'b']}],
"mostrar": [{'pattern': 'o-ue', 'stems': ['m', 'str']}],
"poblar": [{'pattern': 'o-ue', 'stems': ['p', 'bl']}],
"premostrar": [{'pattern': 'o-ue', 'stems': ['prem', 'str']}],
"probar": [{'pattern': 'o-ue', 'stems': ['pr', 'b']}],
"recolar": [{'pattern': 'o-ue', 'stems': ['rec', 'l']}],
"recontar": [{'pattern': 'o-ue', 'stems': ['rec', 'nt']}],
"recordar": [{'pattern': 'o-ue', 'stems': ['rec', 'rd']}],
"recostar": [{'pattern': 'o-ue', 'stems': ['rec', 'st']}],
"reencontrar": [{'pattern': 'o-ue', 'stems': ['reenc', 'ntr']}],
"renovar": [{'pattern': 'o-ue', 'stems': ['ren', 'v']}],
"repoblar": [{'pattern': 'o-ue', 'stems': ['rep', 'bl']}],
"reprobar": [{'pattern': 'o-ue', 'stems': ['repr', 'b']}],
"resollar": [{'pattern': 'o-ue', 'stems': ['res', 'll']}],
"resonar": [{'pattern': 'o-ue', 'stems': ['res', 'n']}],
"revolar": [{'pattern': 'o-ue', 'stems': ['rev', 'l']}],
"rodar": [{'pattern': 'o-ue', 'stems': ['r', 'd']}],
"sobrepoblar": [{'pattern': 'o-ue', 'stems': ['sobrep', 'bl']}],
"sobrevolar": [{'pattern': 'o-ue', 'stems': ['sobrev', 'l']}],
"solar": [{'pattern': 'o-ue', 'stems': ['s', 'l']}],
"soldar": [{'pattern': 'o-ue', 'stems': ['s', 'ld']}],
"soltar": [{'pattern': 'o-ue', 'stems': ['s', 'lt']}],
"sonar": [{'pattern': 'o-ue', 'stems': ['s', 'n']}],
"soñar": [{'pattern': 'o-ue', 'stems': ['s', 'ñ']}],
"tostar": [{'pattern': 'o-ue', 'stems': ['t', 'st']}],
"tronar": [{'pattern': 'o-ue', 'stems': ['tr', 'n']}],
"volar": [{'pattern': 'o-ue', 'stems': ['v', 'l']}],
"acensuar": [{'pattern': 'u-ú', 'stems': ['acens', '']}],
"acentuar": [{'pattern': 'u-ú', 'stems': ['acent', '']}],
"actuar": [{'pattern': 'u-ú', 'stems': ['act', '']}],
"adecuar": [{'pattern': 'u-ú', 'stems': ['adec', '']}, {'pattern': '', 'stems': ['adecu']}],
"ahumar": [{'pattern': 'u-ú', 'stems': ['ah', 'm']}],
"ahusar": [{'pattern': 'u-ú', 'stems': ['ah', 's']}],
"arruar": [{'pattern': 'u-ú', 'stems': ['arr', '']}],
"atenuar": [{'pattern': 'u-ú', 'stems': ['aten', '']}],
"aullar": [{'pattern': 'u-ú', 'stems': ['a', 'll']}],
"aunar": [{'pattern': 'u-ú', 'stems': ['a', 'n']}],
"aupar": [{'pattern': 'u-ú', 'stems': ['a', 'p']}],
"autoevacuarse": [{'pattern': 'u-ú', 'stems': ['autoevac', '']}, {'pattern': '', 'stems': ['autoevacu']}],
"autoevaluarse": [{'pattern': 'u-ú', 'stems': ['autoeval']}],
"avaluar": [{'pattern': 'u-ú', 'stems': ['aval']}],
"coactuar": [{'pattern': 'u-ú', 'stems': ['coact', '']}],
"conceptuar": [{'pattern': 'u-ú', 'stems': ['concept', '']}],
"conflictuar": [{'pattern': 'u-ú', 'stems': ['conflict']}],
"consensuar": [{'pattern': 'u-ú', 'stems': ['consens', '']}],
"contextuar": [{'pattern': 'u-ú', 'stems': ['context']}],
"continuar": [{'pattern': 'u-ú', 'stems': ['contin', '']}],
"desconceptuar": [{'pattern': 'u-ú', 'stems': ['desconcept']}],
"descontinuar": [{'pattern': 'u-ú', 'stems': ['descontin', '']}],
"deshabituar": [{'pattern': 'u-ú', 'stems': ['deshabit']}],
"desvirtuar": [{'pattern': 'u-ú', 'stems': ['desvirt', '']}],
"devaluar": [{'pattern': 'u-ú', 'stems': ['deval', '']}],
"discontinuar": [{'pattern': 'u-ú', 'stems': ['discontin', '']}],
"efectuar": [{'pattern': 'u-ú', 'stems': ['efect', '']}],
"embaular": [{'pattern': 'u-ú', 'stems': ['emba', 'l']}],
"evacuar": [{'pattern': 'u-ú', 'stems': ['evac', '']}, {'pattern': '', 'stems': ['evacu']}],
"evaluar": [{'pattern': 'u-ú', 'stems': ['eval', '']}],
"exceptuar": [{'pattern': 'u-ú', 'stems': ['except', '']}],
"extenuar": [{'pattern': 'u-ú', 'stems': ['exten', '']}],
"fluctuar": [{'pattern': 'u-ú', 'stems': ['fluct', '']}],
"graduar": [{'pattern': 'u-ú', 'stems': ['grad', '']}],
"habituar": [{'pattern': 'u-ú', 'stems': ['habit', '']}],
"infatuar": [{'pattern': 'u-ú', 'stems': ['infat', '']}],
"insinuar": [{'pattern': 'u-ú', 'stems': ['insin', '']}],
"interactuar": [{'pattern': 'u-ú', 'stems': ['interact', '']}],
"licuar": [{'pattern': '', 'stems': ['licu']}, {'pattern': 'u-ú', 'stems': ['lic', '']}],
"maullar": [{'pattern': 'u-ú', 'stems': ['ma', 'll']}],
"menstruar": [{'pattern': 'u-ú', 'stems': ['menstr', '']}],
"perpetuar": [{'pattern': 'u-ú', 'stems': ['perpet', '']}],
"preceptuar": [{'pattern': 'u-ú', 'stems': ['precept', '']}],
"promiscuar": [{'pattern': 'u-ú', 'stems': ['promisc']}],
"puntuar": [{'pattern': 'u-ú', 'stems': ['punt', '']}],
"readecuar": [{'pattern': 'u-ú', 'stems': ['readec', '']}, {'pattern': '', 'stems': ['readecu']}],
"redituar": [{'pattern': 'u-ú', 'stems': ['redit']}],
"reevaluar": [{'pattern': 'u-ú', 'stems': ['reeval', '']}],
"rehusar": [{'pattern': 'u-ú', 'stems': ['reh', 's']}],
"resituar": [{'pattern': 'u-ú', 'stems': ['resit', '']}],
"reusar": [{'pattern': 'u-ú', 'stems': ['re', 's']}],
"revaluar": [{'pattern': 'u-ú', 'stems': ['reval', '']}],
"sahumar": [{'pattern': 'u-ú', 'stems': ['sah', 'm']}],
"situar": [{'pattern': 'u-ú', 'stems': ['sit', '']}],
"sobreactuar": [{'pattern': 'u-ú', 'stems': ['sobreact', '']}],
"subvaluar": [{'pattern': 'u-ú', 'stems': ['subval', '']}],
"tatuar": [{'pattern': 'u-ú', 'stems': ['tat', '']}],
"tumultuar": [{'pattern': 'u-ú', 'stems': ['tumult', '']}],
"usufructuar": [{'pattern': 'u-ú', 'stems': ['usufruct']}],
"valuar": [{'pattern': 'u-ú', 'stems': ['val', '']}],
"diluviar": [{'pattern': 'imp', 'stems': ['diluvi']}],
"atardecer": [{'pattern': 'atardecer', 'stems': ['atarde']}],
"empecer": [{'pattern': 'atardecer', 'stems': ['empe']}],
"atañer": [{'pattern': 'atañer', 'stems': ['atañ']}],
"caber": [{'pattern': 'caber', 'stems': ['']}],
"caer": [{'pattern': 'caer', 'stems': ['']}],
"decaer": [{'pattern': 'caer', 'stems': ['de']}],
"recaer": [{'pattern': 'caer', 'stems': ['re']}],
"haber": [{'pattern': 'haber', 'stems': ['']}],
"calefacer": [{'pattern': 'hacer', 'stems': ['calef']}],
"deshacer": [{'pattern': 'hacer', 'stems': ['desh']}],
"facer": [{'pattern': 'hacer', 'stems': ['f']}],
"hacer": [{'pattern': 'hacer', 'stems': ['h']}],
"jacer": [{'pattern': 'hacer', 'stems': ['j']}],
"satisfacer": [{'pattern': 'hacer', 'stems': ['satisf']}],
"valefacer": [{'pattern': 'hacer', 'stems': ['valef']}],
"complacer": [{'pattern': 'placer', 'stems': ['com']}],
"placer": [{'pattern': 'placer', 'stems': ['']}],
"poder": [{'pattern': 'poder', 'stems': []}],
"anteponer": [{'pattern': '-poner', 'stems': ['ante']}],
"aponer": [{'pattern': '-poner', 'stems': ['a']}],
"autoimponerse": [{'pattern': '-poner', 'stems': ['autoim']}],
"componer": [{'pattern': '-poner', 'stems': ['com']}],
"contraponer": [{'pattern': '-poner', 'stems': ['contra']}],
"deponer": [{'pattern': '-poner', 'stems': ['de']}],
"descomponer": [{'pattern': '-poner', 'stems': ['descom']}],
"disponer": [{'pattern': '-poner', 'stems': ['dis']}],
"exponer": [{'pattern': '-poner', 'stems': ['ex']}],
"imponer": [{'pattern': '-poner', 'stems': ['im']}],
"indisponer": [{'pattern': '-poner', 'stems': ['indis']}],
"interponer": [{'pattern': '-poner', 'stems': ['inter']}],
"malponer": [{'pattern': '-poner', 'stems': ['mal']}],
"oponer": [{'pattern': '-poner', 'stems': ['o']}],
"poner": [{'pattern': 'poner', 'stems': []}],
"posponer": [{'pattern': '-poner', 'stems': ['pos']}],
"predisponer": [{'pattern': '-poner', 'stems': ['predis']}],
"presuponer": [{'pattern': '-poner', 'stems': ['presu']}],
"proponer": [{'pattern': '-poner', 'stems': ['pro']}],
"recomponer": [{'pattern': '-poner', 'stems': ['recom']}],
"reimponer": [{'pattern': '-poner', 'stems': ['reim']}],
"reponer": [{'pattern': '-poner', 'stems': ['re']}],
"sobreponer": [{'pattern': '-poner', 'stems': ['sobre']}],
"superimponer": [{'pattern': '-poner', 'stems': ['superim']}],
"superponer": [{'pattern': '-poner', 'stems': ['super']}],
"suponer": [{'pattern': '-poner', 'stems': ['su']}],
"transponer": [{'pattern': '-poner', 'stems': ['trans']}],
"trasponer": [{'pattern': '-poner', 'stems': ['tras']}],
"yuxtaponer": [{'pattern': '-poner', 'stems': ['yuxta']}],
"malquerer": [{'pattern': 'querer', 'stems': ['mal']}],
"querer": [{'pattern': 'querer', 'stems': ['']}],
"raer": [{'pattern': 'raer', 'stems': []}],
"corroer": [{'pattern': 'roer', 'stems': ['cor']}],
"roer": [{'pattern': 'roer', 'stems': ['']}],
"romper": [{'pattern': 'romper', 'stems': []}],
"resaber": [{'pattern': 'saber', 'stems': ['re']}],
"saber": [{'pattern': 'saber', 'stems': ['']}],
"ser": [{'pattern': 'ser', 'stems': []}],
"soler": [{'pattern': 'soler', 'stems': []}],
"abstener": [{'pattern': '-tener', 'stems': ['abs']}],
"atener": [{'pattern': '-tener', 'stems': ['a']}],
"contener": [{'pattern': '-tener', 'stems': ['con']}],
"detener": [{'pattern': '-tener', 'stems': ['de']}],
"entretener": [{'pattern': '-tener', 'stems': ['entre']}],
"mantener": [{'pattern': '-tener', 'stems': ['man']}],
"manutener": [{'pattern': '-tener', 'stems': ['manu']}],
"obtener": [{'pattern': '-tener', 'stems': ['ob']}],
"pertener": [{'pattern': 'tener', 'stems': ['per']}],
"retener": [{'pattern': '-tener', 'stems': ['re']}],
"sostener": [{'pattern': '-tener', 'stems': ['sos']}],
"tener": [{'pattern': 'tener', 'stems': ['']}],
"abstraer": [{'pattern': 'traer', 'stems': ['abstra']}],
"atraer": [{'pattern': 'traer', 'stems': ['atra']}],
"contraer": [{'pattern': 'traer', 'stems': ['contra']}],
"detraer": [{'pattern': 'traer', 'stems': ['detra']}],
"distraer": [{'pattern': 'traer', 'stems': ['distra']}],
"extraer": [{'pattern': 'traer', 'stems': ['extra']}],
"maltraer": [{'pattern': 'traer', 'stems': ['maltra']}],
"retraer": [{'pattern': 'traer', 'stems': ['retra']}],
"retrotraer": [{'pattern': 'traer', 'stems': ['retrotra']}],
"substraer": [{'pattern': 'traer', 'stems': ['substra']}],
"sustraer": [{'pattern': 'traer', 'stems': ['sustra']}],
"traer": [{'pattern': 'traer', 'stems': ['tra']}],
"equivaler": [{'pattern': 'valer', 'stems': ['equi']}],
"prevaler": [{'pattern': 'valer', 'stems': ['pre']}],
"valer": [{'pattern': 'valer', 'stems': ['']}],
"antever": [{'pattern': 'ver e-é', 'stems': ['ante']}],
"entrever": [{'pattern': 'ver e-é', 'stems': ['entre']}],
"prever": [{'pattern': 'ver e-é', 'stems': ['pre']}],
"rever": [{'pattern': 'ver e-é', 'stems': ['re']}],
"ver": [{'pattern': 'ver', 'stems': []}],
"adyacer": [{'pattern': 'yacer', 'stems': ['ad']}],
"subyacer": [{'pattern': 'yacer', 'stems': ['sub']}],
"yacer": [{'pattern': 'yacer', 'stems': ['']}],
"convencer": [{'pattern': '-cer', 'stems': ['conven']}],
"ejercer": [{'pattern': '-cer', 'stems': ['ejer']}],
"mecer": [{'pattern': '-cer', 'stems': ['me']}],
"mulcer": [{'pattern': '-cer', 'stems': ['mul']}],
"remecer": [{'pattern': '-cer', 'stems': ['reme']}],
"revencer": [{'pattern': '-cer', 'stems': ['reven']}],
"vencer": [{'pattern': '-cer', 'stems': ['ven']}],
"acreer": [{'pattern': '-eer', 'stems': ['acr']}],
"creer": [{'pattern': '-eer', 'stems': ['cr']}],
"descreer": [{'pattern': '-eer', 'stems': ['descr']}],
"desposeer": [{'pattern': 'poseer', 'stems': ['despos']}],
"desproveer": [{'pattern': '-eer', 'stems': ['desprov']}],
"leer": [{'pattern': '-eer', 'stems': ['l']}],
"peer": [{'pattern': '-eer', 'stems': ['p']}],
"poseer": [{'pattern': '-eer', 'stems': ['pos']}],
"proveer": [{'pattern': 'proveer', 'stems': ['prov']}],
"releer": [{'pattern': '-eer', 'stems': ['rel']}],
"sobreseer": [{'pattern': '-eer', 'stems': ['sobres']}],
"absterger": [{'pattern': '-ger', 'stems': ['abster']}],
"acoger": [{'pattern': '-ger', 'stems': ['aco']}],
"antecoger": [{'pattern': '-ger', 'stems': ['anteco']}],
"auger": [{'pattern': '-ger', 'stems': ['au']}],
"autoprotegerse": [{'pattern': '-ger', 'stems': ['autoprote']}],
"coger": [{'pattern': '-ger', 'stems': ['co']}],
"converger": [{'pattern': '-ger', 'stems': ['conver']}],
"descoger": [{'pattern': '-ger', 'stems': ['desco']}],
"desproteger": [{'pattern': '-ger', 'stems': ['desprote']}],
"deterger": [{'pattern': '-ger', 'stems': ['deter']}],
"emerger": [{'pattern': '-ger', 'stems': ['emer']}],
"emulger": [{'pattern': '-ger', 'stems': ['emul']}],
"emunger": [{'pattern': '-ger', 'stems': ['emun']}],
"encoger": [{'pattern': '-ger', 'stems': ['enco']}],
"escoger": [{'pattern': '-ger', 'stems': ['esco']}],
"minger": [{'pattern': '-ger', 'stems': ['min']}],
"mulger": [{'pattern': '-ger', 'stems': ['mul']}],
"proteger": [{'pattern': '-ger', 'stems': ['prote']}],
"recoger": [{'pattern': '-ger', 'stems': ['reco']}],
"sobrecoger": [{'pattern': '-ger', 'stems': ['sobreco']}],
"sobreproteger": [{'pattern': '-ger', 'stems': ['sobreprote']}],
"absolver": [{'pattern': '-olver', 'stems': ['abs']}],
"autodisolverse": [{'pattern': '-olver', 'stems': ['autodis']}],
"bolver": [{'pattern': '-olver', 'stems': ['b']}],
"desenvolver": [{'pattern': '-olver', 'stems': ['desenv']}],
"devolver": [{'pattern': '-olver', 'stems': ['dev']}],
"disolver": [{'pattern': '-olver', 'stems': ['dis']}],
"envolver": [{'pattern': '-olver', 'stems': ['env']}],
"resolver": [{'pattern': '-olver', 'stems': ['res']}],
"revolver": [{'pattern': '-olver', 'stems': ['rev']}],
"solver": [{'pattern': '-olver', 'stems': ['s']}],
"volver": [{'pattern': '-olver', 'stems': ['v']}],
"empeller": [{'pattern': '-ñer', 'stems': ['empell']}],
"tañer": [{'pattern': '-ñer', 'stems': ['tañ']}],
"toller": [{'pattern': '-ñer', 'stems': ['toll']}, {'pattern': '', 'stems': ['toll']}],
"abastecer": [{'pattern': 'c-zc', 'stems': ['abaste']}],
"aborrecer": [{'pattern': 'c-zc', 'stems': ['aborre']}],
"acaecer": [{'pattern': 'c-zc', 'stems': ['acae']}],
"acontecer": [{'pattern': 'c-zc', 'stems': ['aconte']}],
"acrecer": [{'pattern': 'c-zc', 'stems': ['acre']}],
"adolecer": [{'pattern': 'c-zc', 'stems': ['adole']}],
"adormecer": [{'pattern': 'c-zc', 'stems': ['adorme']}],
"agradecer": [{'pattern': 'c-zc', 'stems': ['agrade']}],
"amanecer": [{'pattern': 'c-zc', 'stems': ['amane']}],
"amarillecer": [{'pattern': 'c-zc', 'stems': ['amarille']}],
"anochecer": [{'pattern': 'c-zc', 'stems': ['anoche']}],
"aparecer": [{'pattern': 'c-zc', 'stems': ['apare']}],
"apetecer": [{'pattern': 'c-zc', 'stems': ['apete']}],
"autoabastecerse": [{'pattern': 'c-zc', 'stems': ['autoabaste']}],
"autoreconocerse": [{'pattern': 'c-zc', 'stems': ['autorecono']}],
"autorreconocerse": [{'pattern': 'c-zc', 'stems': ['autorrecono']}],
"blanquecer": [{'pattern': 'c-zc', 'stems': ['blanque']}],
"carecer": [{'pattern': 'c-zc', 'stems': ['care']}],
"compadecer": [{'pattern': 'c-zc', 'stems': ['compade']}],
"comparecer": [{'pattern': 'c-zc', 'stems': ['compare']}],
"conocer": [{'pattern': 'c-zc', 'stems': ['cono']}],
"convalecer": [{'pattern': 'c-zc', 'stems': ['convale']}],
"crecer": [{'pattern': 'c-zc', 'stems': ['cre']}],
"decrecer": [{'pattern': 'c-zc', 'stems': ['decre']}],
"desabastecer": [{'pattern': 'c-zc', 'stems': ['desabaste']}],
"desagradecer": [{'pattern': 'c-zc', 'stems': ['desagrade']}],
"desaparecer": [{'pattern': 'c-zc', 'stems': ['desapare']}],
"descaecer": [{'pattern': 'c-zc', 'stems': ['descae']}],
"desconocer": [{'pattern': 'c-zc', 'stems': ['descono']}],
"desentumecer": [{'pattern': 'c-zc', 'stems': ['desentume']}],
"desfallecer": [{'pattern': 'c-zc', 'stems': ['desfalle']}],
"desfavorecer": [{'pattern': 'c-zc', 'stems': ['desfavore']}],
"desguarnecer": [{'pattern': 'c-zc', 'stems': ['desguarne']}],
"desmerecer": [{'pattern': 'c-zc', 'stems': ['desmere']}],
"desnacer": [{'pattern': 'nacer', 'stems': ['des']}],
"desobedecer": [{'pattern': 'c-zc', 'stems': ['desobede']}],
"desparecer": [{'pattern': 'c-zc', 'stems': ['despare']}],
"desperecer": [{'pattern': 'c-zc', 'stems': ['despere']}],
"desvanecer": [{'pattern': 'c-zc', 'stems': ['desvane']}],
"embellecer": [{'pattern': 'c-zc', 'stems': ['embelle']}],
"emblanquecer": [{'pattern': 'c-zc', 'stems': ['emblanque']}],
"embravecer": [{'pattern': 'c-zc', 'stems': ['embrave']}],
"embrutecer": [{'pattern': 'c-zc', 'stems': ['embrute']}],
"empalidecer": [{'pattern': 'c-zc', 'stems': ['empalide']}],
"empequeñecer": [{'pattern': 'c-zc', 'stems': ['empequeñe']}],
"empobrecer": [{'pattern': 'c-zc', 'stems': ['empobre']}],
"empodrecer": [{'pattern': 'c-zc', 'stems': ['empodre']}],
"emputecer": [{'pattern': 'c-zc', 'stems': ['empute']}],
"enaltecer": [{'pattern': 'c-zc', 'stems': ['enalte']}],
"enardecer": [{'pattern': 'c-zc', 'stems': ['enarde']}],
"encallecer": [{'pattern': 'c-zc', 'stems': ['encalle']}],
"encanecer": [{'pattern': 'c-zc', 'stems': ['encane']}],
"encarecer": [{'pattern': 'c-zc', 'stems': ['encare']}],
"encarnecer": [{'pattern': 'c-zc', 'stems': ['encarne']}],
"enceguecer": [{'pattern': 'c-zc', 'stems': ['encegue']}],
"endurecer": [{'pattern': 'c-zc', 'stems': ['endure']}],
"enfebrecer": [{'pattern': 'c-zc', 'stems': ['enfebre']}],
"enflaquecer": [{'pattern': 'c-zc', 'stems': ['enflaque']}],
"enfurecer": [{'pattern': 'c-zc', 'stems': ['enfure']}],
"engrandecer": [{'pattern': 'c-zc', 'stems': ['engrande']}],
"engravecer": [{'pattern': 'c-zc', 'stems': ['engrave']}],
"enlentecer": [{'pattern': 'c-zc', 'stems': ['enlente']}],
"enloquecer": [{'pattern': 'c-zc', 'stems': ['enloque']}],
"enmohecer": [{'pattern': 'c-zc', 'stems': ['enmohe']}],
"enmudecer": [{'pattern': 'c-zc', 'stems': ['enmude']}],
"ennegrecer": [{'pattern': 'c-zc', 'stems': ['ennegre']}],
"ennoblecer": [{'pattern': 'c-zc', 'stems': ['ennoble']}],
"enorgullecer": [{'pattern': 'c-zc', 'stems': ['enorgulle']}],
"enrarecer": [{'pattern': 'c-zc', 'stems': ['enrare']}],
"enriquecer": [{'pattern': 'c-zc', 'stems': ['enrique']}],
"enrojecer": [{'pattern': 'c-zc', 'stems': ['enroje']}],
"enronquecer": [{'pattern': 'c-zc', 'stems': ['enronque']}],
"ensoberbecer": [{'pattern': 'c-zc', 'stems': ['ensoberbe']}],
"ensombrecer": [{'pattern': 'c-zc', 'stems': ['ensombre']}],
"ensordecer": [{'pattern': 'c-zc', 'stems': ['ensorde']}],
"entenebrecer": [{'pattern': 'c-zc', 'stems': ['entenebre']}],
"enternecer": [{'pattern': 'c-zc', 'stems': ['enterne']}],
"entontecer": [{'pattern': 'c-zc', 'stems': ['entonte']}],
"entorpecer": [{'pattern': 'c-zc', 'stems': ['entorpe']}],
"entristecer": [{'pattern': 'c-zc', 'stems': ['entriste']}],
"entumecer": [{'pattern': 'c-zc', 'stems': ['entume']}],
"envanecer": [{'pattern': 'c-zc', 'stems': ['envane']}],
"envejecer": [{'pattern': 'c-zc', 'stems': ['enveje']}],
"envilecer": [{'pattern': 'c-zc', 'stems': ['envile']}],
"escaecer": [{'pattern': 'c-zc', 'stems': ['escae']}],
"escarnecer": [{'pattern': 'c-zc', 'stems': ['escarne']}],
"esclarecer": [{'pattern': 'c-zc', 'stems': ['esclare']}],
"esmorecer": [{'pattern': 'c-zc', 'stems': ['esmore']}],
"establecer": [{'pattern': 'c-zc', 'stems': ['estable']}],
"estremecer": [{'pattern': 'c-zc', 'stems': ['estreme']}],
"fallecer": [{'pattern': 'c-zc', 'stems': ['falle']}],
"favorecer": [{'pattern': 'c-zc', 'stems': ['favore']}],
"fenecer": [{'pattern': 'c-zc', 'stems': ['fene']}],
"florecer": [{'pattern': 'c-zc', 'stems': ['flore']}],
"fortalecer": [{'pattern': 'c-zc', 'stems': ['fortale']}],
"fosforecer": [{'pattern': 'c-zc', 'stems': ['fosfore']}],
"guarecer": [{'pattern': 'c-zc', 'stems': ['guare']}],
"guarnecer": [{'pattern': 'c-zc', 'stems': ['guarne']}],
"humedecer": [{'pattern': 'c-zc', 'stems': ['humede']}],
"iñocer": [{'pattern': 'c-zc', 'stems': ['iño']}],
"languidecer": [{'pattern': 'c-zc', 'stems': ['languide']}],
"merecer": [{'pattern': 'c-zc', 'stems': ['mere']}],
"nacer": [{'pattern': 'c-zc', 'stems': ['na']}],
"negrecer": [{'pattern': 'c-zc', 'stems': ['negre']}],
"obedecer": [{'pattern': 'c-zc', 'stems': ['obede']}],
"obscurecer": [{'pattern': 'c-zc', 'stems': ['obscure']}],
"ofrecer": [{'pattern': 'c-zc', 'stems': ['ofre']}],
"oscurecer": [{'pattern': 'c-zc', 'stems': ['oscure']}],
"pacer": [{'pattern': 'c-zc', 'stems': ['pa']}],
"padecer": [{'pattern': 'c-zc', 'stems': ['pade']}],
"palidecer": [{'pattern': 'c-zc', 'stems': ['palide']}],
"parecer": [{'pattern': 'c-zc', 'stems': ['pare']}],
"perecer": [{'pattern': 'c-zc', 'stems': ['pere']}],
"permanecer": [{'pattern': 'c-zc', 'stems': ['permane']}],
"pertenecer": [{'pattern': 'c-zc', 'stems': ['pertene']}],
"preconocer": [{'pattern': 'c-zc', 'stems': ['precono']}],
"preestablecer": [{'pattern': 'c-zc', 'stems': ['preestable']}],
"prevalecer": [{'pattern': 'c-zc', 'stems': ['prevale']}],
"reabastecer": [{'pattern': 'c-zc', 'stems': ['reabaste']}],
"reaparecer": [{'pattern': 'c-zc', 'stems': ['reapare']}],
"reblandecer": [{'pattern': 'c-zc', 'stems': ['reblande']}],
"reconocer": [{'pattern': 'c-zc', 'stems': ['recono']}],
"recrecer": [{'pattern': 'c-zc', 'stems': ['recre']}],
"recrudecer": [{'pattern': 'c-zc', 'stems': ['recrude']}],
"reestablecer": [{'pattern': 'c-zc', 'stems': ['reestable']}],
"rejuvenecer": [{'pattern': 'c-zc', 'stems': ['rejuvene']}],
"renacer": [{'pattern': 'c-zc', 'stems': ['rena']}],
"resplandecer": [{'pattern': 'c-zc', 'stems': ['resplande']}],
"restablecer": [{'pattern': 'c-zc', 'stems': ['restable']}],
"reverdecer": [{'pattern': 'c-zc', 'stems': ['reverde']}],
"robustecer": [{'pattern': 'c-zc', 'stems': ['robuste']}],
"ascender": [{'pattern': 'e-ie', 'stems': ['asc', 'nd']}],
"atender": [{'pattern': 'e-ie', 'stems': ['at', 'nd']}],
"autodefenderse": [{'pattern': 'e-ie', 'stems': ['autodef', 'nd']}],
"cerner": [{'pattern': 'e-ie', 'stems': ['c', 'rn']}],
"condescender": [{'pattern': 'e-ie', 'stems': ['condesc', 'nd']}],
"contender": [{'pattern': 'e-ie', 'stems': ['cont', 'nd']}],
"defender": [{'pattern': 'e-ie', 'stems': ['def', 'nd']}],
"desatender": [{'pattern': 'e-ie', 'stems': ['desat', 'nd']}],
"descender": [{'pattern': 'e-ie', 'stems': ['desc', 'nd']}],
"desentenderse": [{'pattern': 'e-ie', 'stems': ['desent', 'nd']}],
"destender": [{'pattern': 'e-ie', 'stems': ['dest', 'nd']}],
"distender": [{'pattern': 'e-ie', 'stems': ['dist', 'nd']}],
"encender": [{'pattern': 'e-ie', 'stems': ['enc', 'nd']}],
"entender": [{'pattern': 'e-ie', 'stems': ['ent', 'nd']}],
"estender": [{'pattern': 'e-ie', 'stems': ['est', 'nd']}],
"extender": [{'pattern': 'e-ie', 'stems': ['ext', 'nd']}],
"heder": [{'pattern': 'e-ie', 'stems': ['h', 'd']}],
"hender": [{'pattern': 'e-ie', 'stems': ['h', 'nd']}],
"intender": [{'pattern': 'e-ie', 'stems': ['int', 'nd']}],
"malentender": [{'pattern': 'e-ie', 'stems': ['malent', 'nd']}],
"perder": [{'pattern': 'e-ie', 'stems': ['p', 'rd']}],
"sobreentender": [{'pattern': 'e-ie', 'stems': ['sobreent', 'nd']}],
"sobrentender": [{'pattern': 'e-ie', 'stems': ['sobrent', 'nd']}],
"subentender": [{'pattern': 'e-ie', 'stems': ['subent', 'nd']}],
"subtender": [{'pattern': 'e-ie', 'stems': ['subt', 'nd']}],
"tender": [{'pattern': 'e-ie', 'stems': ['t', 'nd']}],
"transcender": [{'pattern': 'e-ie', 'stems': ['transc', 'nd']}],
"trascender": [{'pattern': 'e-ie', 'stems': ['trasc', 'nd']}],
"verter": [{'pattern': 'e-ie', 'stems': ['v', 'rt']}],
"oler": [{'pattern': 'o-hue', 'stems': ['', 'l']}],
"amover": [{'pattern': 'o-ue', 'stems': ['am', 'v']}],
"condolerse": [{'pattern': 'o-ue', 'stems': ['cond', 'l']}],
"conmover": [{'pattern': 'o-ue', 'stems': ['conm', 'v']}],
"demoler": [{'pattern': 'o-ue', 'stems': ['dem', 'l']}],
"doler": [{'pattern': 'o-ue', 'stems': ['d', 'l']}],
"llover": [{'pattern': 'o-ue', 'stems': ['ll', 'v']}],
"moler": [{'pattern': 'o-ue', 'stems': ['m', 'l']}],
"morder": [{'pattern': 'o-ue', 'stems': ['m', 'rd']}],
"mover": [{'pattern': 'o-ue', 'stems': ['m', 'v']}],
"promover": [{'pattern': 'o-ue', 'stems': ['prom', 'v']}],
"remorder": [{'pattern': 'o-ue', 'stems': ['rem', 'rd']}],
"remover": [{'pattern': 'o-ue', 'stems': ['rem', 'v']}],
"asir": [{'pattern': 'asir', 'stems': ['as']}],
"desasir": [{'pattern': 'asir', 'stems': ['desas']}],
"aterir": [{'pattern': 'aterir', 'stems': ['ater']}],
"garantir": [{'pattern': 'aterir', 'stems': ['garant']}],
"antedecir": [{'pattern': 'redecir', 'stems': ['ante']}],
"bendecir": [{'pattern': 'bendecir', 'stems': ['ben']}],
"condecir": [{'pattern': 'predecir', 'stems': ['con']}],
"contradecir": [{'pattern': 'predecir', 'stems': ['contra']}],
"decir": [{'pattern': 'decir', 'stems': ['']}],
"desdecir": [{'pattern': 'predecir', 'stems': ['des']}],
"entredecir": [{'pattern': 'predecir', 'stems': ['entre']}],
"interdecir": [{'pattern': 'redecir', 'stems': ['inter']}],
"maldecir": [{'pattern': 'maldecir', 'stems': ['mal']}],
"predecir": [{'pattern': 'predecir', 'stems': ['pre']}],
"redecir": [{'pattern': 'redecir', 'stems': ['re']}],
"manumitir": [{'pattern': 'manumitir', 'stems': ['manumit']}],
"erguir": [{'pattern': 'erguir', 'stems': []}],
"imprimir": [{'pattern': 'imprimir', 'stems': ['']}],
"reimprimir": [{'pattern': 'imprimir', 'stems': ['re']}],
"sobreimprimir": [{'pattern': 'imprimir', 'stems': ['sobre']}],
"pudrir": [{'pattern': 'pudrir', 'stems': ['pudr']}],
"ir": [{'pattern': 'ir', 'stems': []}],
"rehuir": [{'pattern': 'rehuir', 'stems': []}],
"salir": [{'pattern': 'salir', 'stems': ['']}],
"sobresalir": [{'pattern': 'salir', 'stems': ['sobre']}],
"advenir": [{'pattern': '-venir', 'stems': ['ad']}],
"antevenir": [{'pattern': '-venir', 'stems': ['ante']}],
"avenir": [{'pattern': '-venir', 'stems': ['a']}],
"circunvenir": [{'pattern': '-venir', 'stems': ['circun']}],
"contravenir": [{'pattern': '-venir', 'stems': ['contra']}],
"convenir": [{'pattern': '-venir', 'stems': ['con']}],
"desavenir": [{'pattern': '-venir', 'stems': ['desa']}],
"desconvenir": [{'pattern': '-venir', 'stems': ['descon']}],
"devenir": [{'pattern': '-venir', 'stems': ['de']}],
"entrevenir": [{'pattern': '-venir', 'stems': ['entre']}],
"intervenir": [{'pattern': '-venir', 'stems': ['inter']}],
"invenir": [{'pattern': '-venir', 'stems': ['in']}],
"prevenir": [{'pattern': '-venir', 'stems': ['pre']}],
"provenir": [{'pattern': '-venir', 'stems': ['pro']}],
"reconvenir": [{'pattern': '-venir', 'stems': ['recon']}],
"revenir": [{'pattern': '-venir', 'stems': ['re']}],
"sobrevenir": [{'pattern': '-venir', 'stems': ['sobre']}],
"subvenir": [{'pattern': '-venir', 'stems': ['sub']}],
"supervenir": [{'pattern': '-venir', 'stems': ['super']}],
"venir": [{'pattern': 'venir', 'stems': []}],
"abrir": [{'pattern': '-brir', 'stems': ['a']}],
"codescubrir": [{'pattern': '-brir', 'stems': ['codescu']}],
"cubrir": [{'pattern': '-brir', 'stems': ['cu']}],
"descubrir": [{'pattern': '-brir', 'stems': ['descu']}],
"encubrir": [{'pattern': '-brir', 'stems': ['encu']}],
"entreabrir": [{'pattern': '-brir', 'stems': ['entrea']}],
"reabrir": [{'pattern': '-brir', 'stems': ['rea']}],
"recubrir": [{'pattern': '-brir', 'stems': ['recu']}],
"redescubrir": [{'pattern': '-brir', 'stems': ['redescu']}],
"esparcir": [{'pattern': '-cir', 'stems': ['espar']}],
"estarcir": [{'pattern': '-cir', 'stems': ['estar']}],
"fruncir": [{'pattern': '-cir', 'stems': ['frun']}],
"marcir": [{'pattern': '-cir', 'stems': ['mar']}],
"resarcir": [{'pattern': '-cir', 'stems': ['resar']}],
"rezurcir": [{'pattern': '-cir', 'stems': ['rezur']}],
"surcir": [{'pattern': '-cir', 'stems': ['sur']}],
"uncir": [{'pattern': '-cir', 'stems': ['un']}],
"zurcir": [{'pattern': '-cir', 'stems': ['zur']}],
"abducir": [{'pattern': '-ducir', 'stems': ['ab']}],
"aducir": [{'pattern': '-ducir', 'stems': ['a']}],
"autoconducirse": [{'pattern': '-ducir', 'stems': ['autocon']}],
"autoproducirse": [{'pattern': '-ducir', 'stems': ['autopro']}],
"conducir": [{'pattern': '-ducir', 'stems': ['con']}],
"coproducir": [{'pattern': '-ducir', 'stems': ['copro']}],
"deducir": [{'pattern': '-ducir', 'stems': ['de']}],
"educir": [{'pattern': '-ducir', 'stems': ['e']}],
"inducir": [{'pattern': '-ducir', 'stems': ['in']}],
"introducir": [{'pattern': '-ducir', 'stems': ['intro']}],
"producir": [{'pattern': '-ducir', 'stems': ['pro']}],
"reconducir": [{'pattern': '-ducir', 'stems': ['recon']}],
"reducir": [{'pattern': '-ducir', 'stems': ['re']}],
"reintroducir": [{'pattern': '-ducir', 'stems': ['reintro']}],
"reproducir": [{'pattern': '-ducir', 'stems': ['repro']}],
"retraducir": [{'pattern': '-ducir', 'stems': ['retra']}],
"seducir": [{'pattern': '-ducir', 'stems': ['se']}],
"subducir": [{'pattern': '-ducir', 'stems': ['sub']}],
"traducir": [{'pattern': '-ducir', 'stems': ['tra']}],
"autocorregir": [{'pattern': 'elegir', 'stems': ['autocorr']}],
"colegir": [{'pattern': '-egir', 'stems': ['col']}],
"corregir": [{'pattern': 'elegir', 'stems': ['corr']}],
"elegir": [{'pattern': 'elegir', 'stems': ['el']}],
"recolegir": [{'pattern': '-egir', 'stems': ['recol']}],
"reelegir": [{'pattern': 'elegir', 'stems': ['reel']}],
"regir": [{'pattern': '-egir', 'stems': ['r']}],
"afligir": [{'pattern': '-gir', 'stems': ['afli']}],
"astringir": [{'pattern': '-gir', 'stems': ['astrin']}],
"autoexigirse": [{'pattern': '-gir', 'stems': ['autoexi']}],
"codirigir": [{'pattern': '-gir', 'stems': ['codiri']}],
"compungir": [{'pattern': '-gir', 'stems': ['compun']}],
"confligir": [{'pattern': '-gir', 'stems': ['confli']}],
"convergir": [{'pattern': '-gir', 'stems': ['conver']}],
"dirigir": [{'pattern': '-gir', 'stems': ['diri']}],
"divergir": [{'pattern': '-gir', 'stems': ['diver']}],
"eligir": [{'pattern': '-gir', 'stems': ['eli']}],
"erigir": [{'pattern': '-gir', 'stems': ['eri']}],
"exigir": [{'pattern': '-gir', 'stems': ['exi']}],
"fingir": [{'pattern': '-gir', 'stems': ['fin']}],
"frangir": [{'pattern': '-gir', 'stems': ['fran']}],
"fulgir": [{'pattern': '-gir', 'stems': ['ful']}],
"fungir": [{'pattern': '-gir', 'stems': ['fun']}],
"infligir": [{'pattern': '-gir', 'stems': ['infli']}],
"infringir": [{'pattern': '-gir', 'stems': ['infrin']}],
"inteligir": [{'pattern': '-gir', 'stems': ['inteli']}],
"mugir": [{'pattern': '-gir', 'stems': ['mu']}],
"negligir": [{'pattern': '-gir', 'stems': ['negli']}],
"pungir": [{'pattern': '-gir', 'stems': ['pun']}],
"redirigir": [{'pattern': '-gir', 'stems': ['rediri']}],
"refulgir": [{'pattern': '-gir', 'stems': ['reful']}],
"restringir": [{'pattern': '-gir', 'stems': ['restrin']}],
"resurgir": [{'pattern': '-gir', 'stems': ['resur']}],
"rugir": [{'pattern': '-gir', 'stems': ['ru']}],
"sumergir": [{'pattern': '-gir', 'stems': ['sumer']}],
"surgir": [{'pattern': '-gir', 'stems': ['sur']}],
"transigir": [{'pattern': '-gir', 'stems': ['transi']}],
"ungir": [{'pattern': '-gir', 'stems': ['un']}],
"urgir": [{'pattern': '-gir', 'stems': ['ur']}],
"distinguir": [{'pattern': '-guir', 'stems': ['distin']}],
"extinguir": [{'pattern': '-guir', 'stems': ['extin']}],
"conseguir": [{'pattern': '-guir (e-i)', 'stems': ['cons', '']}],
"perseguir": [{'pattern': '-guir (e-i)', 'stems': ['pers', '']}],
"proseguir": [{'pattern': '-guir (e-i)', 'stems': ['pros', '']}],
"seguir": [{'pattern': '-guir (e-i)', 'stems': ['s', '']}],
"subseguir": [{'pattern': '-guir (e-i)', 'stems': ['subs', '']}],
"argüir": [{'pattern': '-güir', 'stems': ['ar']}],
"reargüir": [{'pattern': '-güir', 'stems': ['rear']}],
"redargüir": [{'pattern': '-güir', 'stems': ['redar']}],
"delinquir": [{'pattern': '-quir', 'stems': ['delin']}],
"derelinquir": [{'pattern': '-quir', 'stems': ['derelin']}],
"derrelinquir": [{'pattern': '-quir', 'stems': ['derrelin']}],
"jaquir": [{'pattern': '-quir', 'stems': ['ja']}],
"adscribir": [{'pattern': '-scribir', 'stems': ['ad']}],
"autodescribirse": [{'pattern': '-scribir', 'stems': ['autode']}],
"circunscribir": [{'pattern': '-scribir', 'stems': ['circun']}],
"coescribir": [{'pattern': '-scribir', 'stems': ['coe']}],
"describir": [{'pattern': '-scribir', 'stems': ['de']}],
"desuscribir": [{'pattern': '-scribir', 'stems': ['desu']}],
"escribir": [{'pattern': '-scribir', 'stems': ['e']}],
"inscribir": [{'pattern': '-scribir', 'stems': ['in']}],
"manuscribir": [{'pattern': '-scribir', 'stems': ['manu']}],
"preinscribir": [{'pattern': '-scribir', 'stems': ['prein']}],
"prescribir": [{'pattern': '-scribir', 'stems': ['pre']}],
"proscribir": [{'pattern': '-scribir', 'stems': ['pro']}],
"redescribir": [{'pattern': '-scribir', 'stems': ['rede']}],
"reescribir": [{'pattern': '-scribir', 'stems': ['ree']}],
"reinscribir": [{'pattern': '-scribir', 'stems': ['rein']}],
"sobreescribir": [{'pattern': '-scribir', 'stems': ['sobree']}],
"sobrescribir": [{'pattern': '-scribir', 'stems': ['sobre']}],
"subscribir": [{'pattern': '-scribir', 'stems': ['sub']}],
"suscribir": [{'pattern': '-scribir', 'stems': ['su']}],
"transcribir": [{'pattern': '-scribir', 'stems': ['tran']}],
"trascribir": [{'pattern': '-scribir', 'stems': ['tra']}],
"abluir": [{'pattern': '-uir', 'stems': ['abl']}],
"afluir": [{'pattern': '-uir', 'stems': ['afl']}],
"atribuir": [{'pattern': '-uir', 'stems': ['atrib']}],
"autodestruirse": [{'pattern': '-uir', 'stems': ['autodestr']}],
"autoexcluirse": [{'pattern': '-uir', 'stems': ['autoexcl']}],
"circuir": [{'pattern': '-uir', 'stems': ['circ']}],
"concluir": [{'pattern': '-uir', 'stems': ['concl']}],
"confluir": [{'pattern': '-uir', 'stems': ['confl']}],
"constituir": [{'pattern': '-uir', 'stems': ['constit']}],
"construir": [{'pattern': '-uir', 'stems': ['constr']}],
"contribuir": [{'pattern': '-uir', 'stems': ['contrib']}],
"deconstruir": [{'pattern': '-uir', 'stems': ['deconstr']}],
"derruir": [{'pattern': '-uir', 'stems': ['derr']}],
"desobstruir": [{'pattern': '-uir', 'stems': ['desobstr']}],
"destituir": [{'pattern': '-uir', 'stems': ['destit']}],
"destruir": [{'pattern': '-uir', 'stems': ['destr']}],
"diluir": [{'pattern': '-uir', 'stems': ['dil']}],
"disminuir": [{'pattern': '-uir', 'stems': ['dismin']}],
"distribuir": [{'pattern': '-uir', 'stems': ['distrib']}],
"eluir": [{'pattern': '-uir', 'stems': ['el']}],
"estatuir": [{'pattern': '-uir', 'stems': ['estat']}],
"excluir": [{'pattern': '-uir', 'stems': ['excl']}],
"extruir": [{'pattern': '-uir', 'stems': ['extr']}],
"fluir": [{'pattern': '-uir', 'stems': ['fl']}],
"fruir": [{'pattern': '-uir', 'stems': ['fr']}],
"huir": [{'pattern': '-uir', 'stems': ['h']}],
"imbuir": [{'pattern': '-uir', 'stems': ['imb']}],
"incluir": [{'pattern': '-uir', 'stems': ['incl']}],
"influir": [{'pattern': '-uir', 'stems': ['infl']}],
"inmiscuirse": [{'pattern': '-uir', 'stems': ['inmisc']}],
"instituir": [{'pattern': '-uir', 'stems': ['instit']}],
"instruir": [{'pattern': '-uir', 'stems': ['instr']}],
"intuir": [{'pattern': '-uir', 'stems': ['int']}],
"obstruir": [{'pattern': '-uir', 'stems': ['obstr']}],
"ocluir": [{'pattern': '-uir', 'stems': ['ocl']}],
"preconstituir": [{'pattern': '-uir', 'stems': ['preconstit']}],
"prostituir": [{'pattern': '-uir', 'stems': ['prostit']}],
"protruir": [{'pattern': '-uir', 'stems': ['protr']}],
"recluir": [{'pattern': '-uir', 'stems': ['recl']}],
"reconstituir": [{'pattern': '-uir', 'stems': ['reconstit']}],
"reconstruir": [{'pattern': '-uir', 'stems': ['reconstr']}],
"redistribuir": [{'pattern': '-uir', 'stems': ['redistrib']}],
"refluir": [{'pattern': '-uir', 'stems': ['refl']}],
"restituir": [{'pattern': '-uir', 'stems': ['restit']}],
"retribuir": [{'pattern': '-uir', 'stems': ['retrib']}],
"substituir": [{'pattern': '-uir', 'stems': ['substit']}],
"sustituir": [{'pattern': 'sustituir', 'stems': ['sustit']}],
"astriñir": [{'pattern': '-ñir', 'stems': ['astriñ']}],
"bruñir": [{'pattern': '-ñir', 'stems': ['bruñ']}],
"bullir": [{'pattern': '-ñir', 'stems': ['bull']}],
"engullir": [{'pattern': '-ñir', 'stems': ['engull']}],
"escabullir": [{'pattern': '-ñir', 'stems': ['escabull']}],
"fuñir": [{'pattern': '-ñir', 'stems': ['fuñ']}],
"gañir": [{'pattern': '-ñir', 'stems': ['gañ']}],
"gruñir": [{'pattern': '-ñir', 'stems': ['gruñ']}],
"mullir": [{'pattern': '-ñir', 'stems': ['mull']}],
"muñir": [{'pattern': '-ñir', 'stems': ['muñ']}],
"plañir": [{'pattern': '-ñir', 'stems': ['plañ']}],
"rebullir": [{'pattern': '-ñir', 'stems': ['rebull']}],
"tullir": [{'pattern': '-ñir', 'stems': ['tull']}],
"zabullir": [{'pattern': '-ñir', 'stems': ['zabull']}],
"zambullir": [{'pattern': '-ñir', 'stems': ['zambull']}],
"çabullir": [{'pattern': '-ñir', 'stems': ['çabull']}],
"arrecir": [{'pattern': 'c-zc', 'stems': ['arre']}],
"autorreproducirse": [{'pattern': 'c-zc', 'stems': ['autorreprodu']}],
"balbucir": [{'pattern': 'c-zc', 'stems': ['balbu']}],
"deslucir": [{'pattern': 'c-zc', 'stems': ['deslu']}],
"enlucir": [{'pattern': 'c-zc', 'stems': ['enlu']}],
"lucir": [{'pattern': 'c-zc', 'stems': ['lu']}],
"relucir": [{'pattern': 'c-zc', 'stems': ['relu']}],
"translucir": [{'pattern': 'c-zc', 'stems': ['translu']}],
"traslucir": [{'pattern': 'c-zc', 'stems': ['traslu']}],
"comedir": [{'pattern': 'e-i', 'stems': ['com', 'd']}],
"competir": [{'pattern': 'e-i', 'stems': ['comp', 't']}],
"concebir": [{'pattern': 'e-i', 'stems': ['conc', 'b']}],
"derretir": [{'pattern': 'e-i', 'stems': ['derr', 't']}],
"descomedir": [{'pattern': 'e-i', 'stems': ['descom', 'd']}],
"despedir": [{'pattern': 'e-i', 'stems': ['desp', 'd']}],
"desvestir": [{'pattern': 'e-i', 'stems': ['desv', 'st']}],
"embestir": [{'pattern': 'e-i', 'stems': ['emb', 'st']}],
"expedir": [{'pattern': 'e-i', 'stems': ['exp', 'd']}],
"gemir": [{'pattern': 'e-i', 'stems': ['g', 'm']}],
"henchir": [{'pattern': 'e-i', 'stems': ['h', 'nch']}],
"impedir": [{'pattern': 'e-i', 'stems': ['imp', 'd']}],
"investir": [{'pattern': 'e-i', 'stems': ['inv', 'st']}],
"medir": [{'pattern': 'e-i', 'stems': ['m', 'd']}],
"pedir": [{'pattern': 'e-i', 'stems': ['p', 'd']}],
"preconcebir": [{'pattern': 'e-i', 'stems': ['preconc', 'b']}],
"reexpedir": [{'pattern': 'e-i', 'stems': ['reexp', 'd']}],
"rendir": [{'pattern': 'e-i', 'stems': ['r', 'nd']}],
"repetir": [{'pattern': 'e-i', 'stems': ['rep', 't']}],
"revestir": [{'pattern': 'e-i', 'stems': ['rev', 'st']}],
"servir": [{'pattern': 'e-i', 'stems': ['s', 'rv']}],
"travestir": [{'pattern': 'e-i', 'stems': ['trav', 'st']}],
"vestir": [{'pattern': 'e-i', 'stems': ['v', 'st']}],
"cernir": [{'pattern': 'e-ie', 'stems': ['c', 'rn']}],
"concernir": [{'pattern': 'concernir', 'stems': ['conc', 'rn']}],
"discernir": [{'pattern': 'e-ie', 'stems': ['disc', 'rn']}],
"hendir": [{'pattern': 'e-ie', 'stems': ['h', 'nd']}],
"adherir": [{'pattern': 'e-ie-i', 'stems': ['adh', 'r']}],
"advertir": [{'pattern': 'e-ie-i', 'stems': ['adv', 'rt']}],
"arrepentir": [{'pattern': 'e-ie-i', 'stems': ['arrep', 'nt']}],
"asentir": [{'pattern': 'e-ie-i', 'stems': ['as', 'nt']}],
"circunferir": [{'pattern': 'e-ie-i', 'stems': ['circunf', 'r']}],
"conferir": [{'pattern': 'e-ie-i', 'stems': ['conf', 'r']}],
"consentir": [{'pattern': 'e-ie-i', 'stems': ['cons', 'nt']}],
"controvertir": [{'pattern': 'e-ie-i', 'stems': ['controv', 'rt']}],
"convertir": [{'pattern': 'e-ie-i', 'stems': ['conv', 'rt']}],
"deferir": [{'pattern': 'e-ie-i', 'stems': ['def', 'r']}],
"desinvertir": [{'pattern': 'e-ie-i', 'stems': ['desinv', 'rt']}],
"desmentir": [{'pattern': 'e-ie-i', 'stems': ['desm', 'nt']}],
"diferir": [{'pattern': 'e-ie-i', 'stems': ['dif', 'r']}],
"digerir": [{'pattern': 'e-ie-i', 'stems': ['dig', 'r']}],
"disentir": [{'pattern': 'e-ie-i', 'stems': ['dis', 'nt']}],
"divertir": [{'pattern': 'e-ie-i', 'stems': ['div', 'rt']}],
"herir": [{'pattern': 'e-ie-i', 'stems': ['h', 'r']}],
"hervir": [{'pattern': 'e-ie-i', 'stems': ['h', 'rv']}],
"inferir": [{'pattern': 'e-ie-i', 'stems': ['inf', 'r']}],
"ingerir": [{'pattern': 'e-ie-i', 'stems': ['ing', 'r']}],
"injerir": [{'pattern': 'e-ie-i', 'stems': ['inj', 'r']}],
"interconvertir": [{'pattern': 'e-ie-i', 'stems': ['interconv', 'rt']}],
"interferir": [{'pattern': 'e-ie-i', 'stems': ['interf', 'r']}],
"invertir": [{'pattern': 'e-ie-i', 'stems': ['inv', 'rt']}],
"malherir": [{'pattern': 'e-ie-i', 'stems': ['malh', 'r']}],
"mentir": [{'pattern': 'e-ie-i', 'stems': ['m', 'nt']}],
"pervertir": [{'pattern': 'e-ie-i', 'stems': ['perv', 'rt']}],
"preferir": [{'pattern': 'e-ie-i', 'stems': ['pref', 'r']}],
"presentir": [{'pattern': 'e-ie-i', 'stems': ['pres', 'nt']}],
"preterir": [{'pattern': 'e-ie-i', 'stems': ['pret', 'r']}],
"proferir": [{'pattern': 'e-ie-i', 'stems': ['prof', 'r']}],
"reconvertir": [{'pattern': 'e-ie-i', 'stems': ['reconv', 'rt']}],
"referir": [{'pattern': 'e-ie-i', 'stems': ['ref', 'r']}],
"reinvertir": [{'pattern': 'e-ie-i', 'stems': ['reinv', 'rt']}],
"requerir": [{'pattern': 'e-ie-i', 'stems': ['requ', 'r']}],
"resentirse": [{'pattern': 'e-ie-i', 'stems': ['res', 'nt']}],
"revertir": [{'pattern': 'e-ie-i', 'stems': ['rev', 'rt']}],
"sentir": [{'pattern': 'e-ie-i', 'stems': ['s', 'nt']}],
"subvertir": [{'pattern': 'e-ie-i', 'stems': ['subv', 'rt']}],
"sugerir": [{'pattern': 'e-ie-i', 'stems': ['sug', 'r']}],
"transferir": [{'pattern': 'e-ie-i', 'stems': ['transf', 'r']}],
"trasferir": [{'pattern': 'e-ie-i', 'stems': ['trasf', 'r']}],
"zaherir": [{'pattern': 'e-ie-i', 'stems': ['zah', 'r']}],
"adquirir": [{'pattern': 'i-ie', 'stems': ['adqu', 'r']}],
"inquirir": [{'pattern': 'i-ie', 'stems': ['inqu', 'r']}],
"perquirir": [{'pattern': 'i-ie', 'stems': ['perqu', 'r']}],
"readquirir": [{'pattern': 'i-ie', 'stems': ['readqu', 'r']}],
"cohibir": [{'pattern': 'i-í', 'stems': ['coh', 'b']}],
"prohibir": [{'pattern': 'i-í', 'stems': ['proh', 'b']}],
"adormir": [{'pattern': 'o-ue', 'stems': ['ad', 'rm']}],
"desmorir": [{'pattern': 'morir', 'stems': ['desm', 'r']}],
"dormir": [{'pattern': 'o-ue', 'stems': ['d', 'rm']}],
"morir": [{'pattern': 'morir', 'stems': ['m', 'r']}],
"premorir": [{'pattern': 'morir', 'stems': ['prem', 'r']}],
"reunir": [{'pattern': 'u-ú', 'stems': ['re', 'n']}],
"desvaír": [{'pattern': 'embaír', 'stems': ['desv']}],
"embaír": [{'pattern': 'embaír', 'stems': ['emb']}],
"desoír": [{'pattern': 'oír', 'stems': ['deso']}],
"entreoír": [{'pattern': 'oír', 'stems': ['entreo']}],
"oír": [{'pattern': 'oír', 'stems': ['o']}],
"trasoír": [{'pattern': 'oír', 'stems': ['traso']}],
"desleír": [{'pattern': '-eír', 'stems': ['desl']}],
"engreír": [{'pattern': '-eír', 'stems': ['engr']}],
"esleír": [{'pattern': '-eír', 'stems': ['esl']}],
"freír": [{'pattern': 'freír', 'stems': ['fr']}],
"refreír": [{'pattern': 'refreír', 'stems': ['refr']}],
"reír": [{'pattern': 'reír', 'stems': ['r']}],
"sofreír": [{'pattern': 'refreír', 'stems': ['sofr']}],
"sonreír": [{'pattern': '-eír', 'stems': ['sonr']}]
}