#!/usr/bin/python3

import argparse
import os
import sys

from spanish_tools.freq import FrequencyList
from spanish_tools.freq import NgramPosProbability
from enwiktionary_wordlist.wordlist import Wordlist
from enwiktionary_wordlist.all_forms import AllForms

import enwiktionary_templates
cachedb = enwiktionary_templates.cache.get_default_cachedb()

def init_freq(params):

    parser = argparse.ArgumentParser(description="Lemmatize frequency list")
    parser.add_argument("--ignore", help="List of words to ignore")
    parser.add_argument("--dictionary", help="Dictionary file name", required=True)
    parser.add_argument("--allforms", help="All-forms file name")
    parser.add_argument("--ngprobs", help="Ngram probability data file")
    parser.add_argument("--ngcase", help="Ngram case probability data file")
    parser.add_argument("--formtypes", help="Create a formtypes list intsead of a lemma list", action='store_true')
    parser.add_argument("--low-mem", help="Use less memory", action='store_true', default=False)
    parser.add_argument("--minuse", help="Only print lemmas with at least N total uses", default=0, type=int)
    parser.add_argument("--infile", help="Usage list")
    parser.add_argument("--outfile", help="outfile (defaults to stdout)", default="-")
    parser.add_argument("--debug", help="debug specific word")
    parser.add_argument("extra", nargs="*", help="Usage list")
    args = parser.parse_args(params)

    ngprobs = NgramPosProbability(args.ngprobs, args.ngcase)

    # allow first positional argument to replace undeclared --infile
    if args.infile == parser.get_default("infile") and args.extra:
        args.infile = args.extra.pop(0)

    args = parser.parse_args(params)

    cache_words = not args.low_mem
    wordlist = Wordlist.from_file(args.dictionary, cache_words=cache_words, template_cachedb=cachedb)

    ignore_data = open(args.ignore) if args.ignore else []

    if args.allforms:
        allforms = AllForms.from_file(args.allforms)
    else:
        allforms = AllForms.from_wordlist(wordlist)

    flist = FrequencyList(wordlist, allforms, ngprobs, ignore_data, debug_word=args.debug)

    if args.ignore:
        ignore_data.close()

    return flist, args

def make_list(flist, infile, outfile, minuse):

    with open(infile) as _infile:
        if outfile and outfile != "-":
            _outfile = open(outfile, "w")
        else:
            _outfile = sys.stdout

        for line in flist.process(_infile, minuse):
            _outfile.write(line)
            _outfile.write("\n")

        if outfile:
            _outfile.close()

def make_formtypes_list(flist, infile, outfile):

    with open(infile) as _infile:
        if outfile and outfile != "-":
            _outfile = open(outfile, "w")
        else:
            _outfile = sys.stdout

        for line in flist.formtypes(_infile):
            _outfile.write(line)
            _outfile.write("\n")

        if outfile:
            _outfile.close()

def build_freq(params=None):
    flist, args = init_freq(params)
    if args.formtypes:
        make_formtypes_list(flist, args.infile, args.outfile)
    else:
        make_list(flist, args.infile, args.outfile, args.minuse)

if __name__ == "__main__":
    build_freq(sys.argv[1:])
